name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    if: success()
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          ssh user@your-server "cd /var/www/task-management-api && git pull origin main && npm install && pm2 restart all"
